[workspace]
members = [
    "binx-core",
    "binx-multigwas",
    "binx-kinship",
    "binx-cli",
    "binx-dosage",
    "binx-convert",
    "binx-plotting",
    "rrblup-rs",
    "gwaspoly-rs",
]

resolver = "2"
