[package]
name = "binx-gwas"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Biallelic GWAS (GWASpoly-like) for binx"

[dependencies]
anyhow = "1"
ndarray = "0.15"
statrs = "0.16"
binx-core = { path = "../binx-core" }
csv = "1.3"
